FROM ubuntu:latest

RUN apt-get update
RUN apt-get install -y python3 python3-pip

RUN pip3 install --break-system-packages flask

ENV DB_PASSWORD="db_password"
ENV API_KEY="api_key"

COPY . /app
WORKDIR /app

CMD ["python3", "app.py"]
