name: CS102 Workflow

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.11.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black mypy pandas boddle pytest nltk pymorphy3 deep-translator scikit-learn
    - name: Download NLTK data
      run: |
        python -c "import nltk; nltk.download('stopwords')"
    - name: Install project dependencies
      run: |
        if [ -f ${{ github.head_ref }}/requirements.txt ];
        then
          pip install -r ${{ github.head_ref }}/requirements.txt
        fi
    - name: Run unittests
      run: |
        python -m pytest